### ISSUE TITLE
functions don't provide or throw errors

### ISSUE THREAD

**Issue by stevenvachon** [xxoo/node-fswin#10]
node "fs" package throws errors on sync functions and provides an error argument in async functions.

```js
console.log( fswin.setAttributesSync("./non-existent-file", {"IS_HIDDEN":true}) );  //-> false
```

The above should've thrown an error.

**Comment by stevenvachon** [comment]
Oops, nevermind. I was calling `setAttributes()` instead of `setAttributesSync()` and was getting a returned value of `true`.

**Comment by stevenvachon** [comment]
However, throwing or returning errors would definitely be more helpful. Consider this:
```js
var error;

error = fswin.setAttributesSync("./non-existent-file", {"IS_HIDDEN":true});
console.log(error);  //-> [Error: File not found.]

error = fswin.setAttributesSync("./real-file", {"IS_HIDDEN":true});
console.log(error);  //-> null
```

**Comment by stevenvachon** [comment]
Parity with node errors would be sweet, but not necessary.

**Comment by xxoo** [comment]
it's too complex to find out what kind of error occurs...
