### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by stevenvachon** [xxoo/node-fswin#11]
```
Uncaught Error: Module did not self-register.
      at Error (native)
      at Object.<anonymous> (C:\projects\winattr\lib\binding\index.js:2:13)
      at Object.change (C:\projects\winattr\lib\whichLib.js:25:20)
      at switchLib (C:\projects\winattr\test\util.js:198:12)
      at C:\projects\winattr\test\util.js:53:3
      at FSReqWrap.oncomplete (fs.js:82:15)
```
https://ci.appveyor.com/project/stevenvachon/winattr/build/job/93nr8xhqxqvamlw7

**Comment by stevenvachon** [comment]
If Appveyor is to blame, please tell them in the discussion: http://help.appveyor.com/discussions/problems/2667-iojs-not-loading-binding

**Comment by xxoo** [comment]
sorry i'm not sure about what exactly course the error.
what i know is, after calling
```
require('fswin');
```
the call stack should goto `fswin/index.js`
but i don't see it in the log

**Comment by stevenvachon** [comment]
Can you try testing with AppVeyor? It'd probably be a good idea as it's the free Windows-based CI that the Node/IO community uses.

**Comment by stevenvachon** [comment]
My error points to line 2 of one of my files. That line looks like this:
```js
var fswin = require("fswin");
```

**Comment by stevenvachon** [comment]
What makes it more confusing is that I have a try/catch around the `require()` for that file (which loads fswin). The error should have been caught.

**Comment by stevenvachon** [comment]
My tests are strict and will throw -- I'd forgotten. Removing the above comment.

**Comment by stevenvachon** [comment]
This could be a exposing an fswin issue with other Windows-based environments.

**Comment by JCMais** [comment]
You should not use the node executable when building with io.js, if you do, the native module needs to be built with the win_delay_load_hook (https://github.com/TooTallNate/node-gyp/blob/master/addon.gypi#L4) set to true. See https://github.com/nodejs/node/issues/751

Here is one way to use appveyor without that error: https://github.com/nodejs/nan/blob/master/appveyor.yml#L32 You check the version first, and then you call the correct binary afterwards.

**Comment by stevenvachon** [comment]
@JCMais thanks! You might find this informative: http://help.appveyor.com/discussions/problems/2667-iojs-not-loading-binding#comment_37684231
