### ISSUE TITLE
setAttributesSync() is not working for folder

### ISSUE THREAD

**Issue by unional** [xxoo/node-fswin#14]
folder: `E:\projects\test`:
```sh
+ README.md
+ file1.txt
```

```js
var fswin = require('fswin');

// Working for file
fswin.setAttributesSync('E:\\projects\\test\\README.md', {IS_READ_ONLY: false});

// Not working for folder
fswin.setAttributesSync('E:\\projects\\test', {IS_READ_ONLY: false});
fswin.setAttributesSync('E:\\projects\\test\\', {IS_READ_ONLY: false});
```

**Comment by unional** [comment]
Never mind. Realized you are working on the directory, not `./*`

**Comment by xxoo** [comment]
the only attribute effect to directories is IS_HIDDEN. others are always false even if you have set to true.
this seems like a system level limition. and no way to bypass.

**Comment by xxoo** [comment]
yea this method changes the directory's own attributes
