### ISSUE TITLE
Error loading using devtool (Electron)

### ISSUE THREAD

**Issue by dongryphon** [xxoo/node-fswin#15]
Greetings,

First off thanks for the awesome module! I have been using it a bit in my [project](https://www.npmjs.com/package/phylo) and am hitting a snag when I try to use it in the [devtool](https://www.npmjs.com/package/devtool) debugger. In particular, I get this error:

```
Q:\Data\Don\Git\phylo\node_modules\fswin\index.js
The specified procedure could not be found.
\\?\Q:\Data\Don\Git\phylo\node_modules\fswin\6.x.x\x64\fswin.node
```
I recently upgraded to latest of everything to make sure that wasn't the issue:
```
> node -v
v7.4.0

> npm -v
4.0.5

> devtool -v

devtool 2.3.0
electron 1.4.3
node 6.5.0
chrome 53.0.2785.113
```
I also removed `node_modules` and ran a fresh `npm install`. Curiously, the error I was getting before all that was "Module did not self-register" (https://github.com/xxoo/node-fswin/issues/11) but now I get the above.

I suspect this is an issue with Electron which is also a big target for my work.

Any ideas?

**Comment by xxoo** [comment]
I think electron requires different build environment for native addons. which means the pre-built binaries don't work with it. I'll add electron binaries in the next relaese. but now you can follow this article to build your own
http://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by dongryphon** [comment]
That's awesome to hear! Any ballpark when the next release may be? Thanks!

**Comment by xxoo** [comment]
i guess it will be right after node 8.0 if there's no emergency bug found

**Comment by scedge** [comment]
I have had zero luck manually building, have any of you had success?

**Comment by sebn** [comment]
@xxoo Hello there, thanks for the nice package!

I believe the released npm package does not include the C++ sources, which prevents rebuilding for electron after installing through npm (e.g. using electron-rebuild).

Also not having a package.json prevents adding the git repo as an npm dependency.

Providing those could make fswin easier to build from sources without even having to provide electron-specific binaries. Most people should probably rebuild anyway, as suggested in the tutorial.

**Comment by xxoo** [comment]
@sebn I'm not sure how electron-rebuild works, but the npm package does contain a package.json with the repository url configured. and also with binaries for electron 1.3.x - 1.6.x now.
I agree that most people should build from source, but unfortunately most windows users don't have the required build environment...

**Comment by sebn** [comment]
> the npm package does contain a package.json

Sure, I assume that's the one generated by node-gyp? But when you temporarily fork to fix some issue, e.g. `npm add fswin@sebn/node-fswin#electron`, npm complains that the repo does not contain a manifest. Adding a `package.json` solved the issue. I'm not sure how node-gyp merges the source `package.json` fields with the generated ones though.

> with binaries for electron 1.3.x - 1.6.x now.

Wow, that's great! Thank you!
In my case, I accidentally switched to 1.7.x though, so I'll still need to rebuild from sources.

> most windows users don't have the required build environment...

I believe `npm install -g windows-build-tools` just works nowadays, and is [quite well documented](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules)

Those were just suggestions, thank you very much for your answer and for your work (which makes my life easier)! 😄

**Comment by xxoo** [comment]
ok i see, the package.json is added to this repo now
