### ISSUE TITLE
Compiling for electron fails

### ISSUE THREAD

**Issue by scedge** [xxoo/node-fswin#16]
Running on Win10, Node 7.8.0 and node-gyp 3.6.0. Following the guide found[ here ](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) running this command
`node-gyp rebuild --target=1.6.2 --arch=x64 --dist-url=https://atom.io/download/electron` produces this error.

![cmd_2017-04-03_15-11-01](https://cloud.githubusercontent.com/assets/8292753/24629853/1dbc42bc-1880-11e7-89d8-d81aca390c81.png)

**Comment by xxoo** [comment]
@scedge I've updated the source, but I can't test it by now. please try again and let me know if it works. thanks

**Comment by scedge** [comment]
Works perfectly! I ran the command I originally mentioned but this time it finished without errors, it generated a new fswin.node file which I used that file to replace the one in my electron app located in `node_modules\fswin\7.x.x\x64` and was able to read file properties.

Thanks for the fix.
