### ISSUE TITLE
Update Electron support

### ISSUE THREAD

**Issue by matthew-matvei** [xxoo/node-fswin#18]
I recently updated my Electron app [FreeMAN](https://github.com/matthew-matvei/freeman) to v1.8.x. This package seems very coupled to certain versions of Electron, and does not currently support v1.8.x.

Rather than packaging compiled binaries, you could distribute the source code that consumers could then build using `electron-rebuild`. I suppose doing the same with Node would be optional, given the way the `index.js` is currently written.

The quick yet less elegant solution would be to add v1.8.x Electron support in the same way you have other versions.

**Comment by matthew-matvei** [comment]
In order to keep working on my app, I've forked this repo and made an [npm package](https://www.npmjs.com/package/electron-fswin) that works fairly well for me. Let me know what you'd like to happen with this, if you have any thoughts (attributions etc.). The forked and renamed repo can be found [here](https://github.com/matthew-matvei/electron-fswin)

**Comment by xxoo** [comment]
@matthew-matvei thanks for using fswin. i'm planing to rewite this project with n-api to avoid this kind of problems when it becomes stable. and i'm really glad to know your work. every thing is good, please keep doing it.

**Comment by xxoo** [comment]
now it should be working with electron 2.0 and later. 1.8.x might need some command line flag to enable n-api support.
