### ISSUE TITLE
dirWatcher options are invalid

### ISSUE THREAD

**Issue by eunikitin** [xxoo/node-fswin#19]
fswin.dirWatcher.options duplicates fswin.dirWatcher.events:

![image](https://user-images.githubusercontent.com/2767639/39672666-564ac400-5137-11e8-8e47-944d806cf344.png)

I copy-pasted the example code from [this docs section](https://github.com/xxoo/node-fswin/wiki/dirWatcher), and it has issues related with the problem i described before:

![image](https://user-images.githubusercontent.com/2767639/39672705-303f820e-5138-11e8-9546-1d6a6a5de3f6.png)

Tip: To temporary fix this you can change options object structure like this:

```js
const options = {
  WATCH_SUB_DIRECTORIES: true,  // watch the directory tree
  CHANGE_FILE_SIZE:      true,  // watch file size changes, will fire in 'MODIFIED' event
  CHANGE_LAST_WRITE:     true,  // watch last write time changes, will fire in 'MODIFIED' event
  CHANGE_LAST_ACCESS:    false, // watch last access time changes, will fire in 'MODIFIED' event
  CHANGE_CREATION:       false, // watch creation time changes, will fire in 'MODIFIED' event
  CHANGE_ATTRIBUTES:     false, // watch attributes changes, will fire in 'MODIFIED' event
  CHANGE_SECURITY:       false  // watch security changes, will fire in 'MODIFIED' event;
};
```

P.S. Thanks for awesome lib

**Comment by xxoo** [comment]
thanks for using fswin. i'm currently rewriting it with n-api, and considering removing these properties. since people don't really use them.

**Comment by xxoo** [comment]
document fixed.
