### ISSUE TITLE
Node 10 support

### ISSUE THREAD

**Issue by ArgonAlex** [xxoo/node-fswin#20]
I'm getting `Error: Cannot find module './node/10.x.x/x64/fswin.node'` when trying to require fswin. And indeed the `node` folder in the fswin package directory only contains up to 9.x.x. I'm seeing the same result installing with either yarn or npm.

Environment:
node 10.5.0
npm 6.1.0
yarn 1.7.0
node-gyp 3.7.0

**Comment by xxoo** [comment]
sorry, kind of busy these days...
a month ago, i was waiting for the async functions in napi that seems are arrival now.
guess i may finish rewriting this project in a week.
please be a little more patient...

**Comment by xxoo** [comment]
it's just a little bit longer then a week but finally released
^_^
