### ISSUE TITLE
Support FILE_ATTRIBUTE_SPARSE_FILE

### ISSUE THREAD

**Issue by RangerMauve** [xxoo/node-fswin#25]
There's a lot of use for having sparse files enabled on Windows, which doesn't seem to be possible in node's regular FS API.

Specifically, the [FILE_ATTRIBUTE_SPARSE_FILE](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_sparse) attribute toggles this.

Specifically, this would be useful for [random-access-file](https://github.com/random-access-storage/random-access-file/issues/23) which is often used for storing large sparse files.

Would a PR that adds this attribute to [setAttributes.h](https://github.com/xxoo/node-fswin/blob/master/src/setAttributes.h) be welcome?

**Comment by xxoo** [comment]
Sure. I'd like to have more useful api implanted. And adding it to setAttributes might be the best way for user (compare to a new api). Please send your pr, thanks!

**Comment by xori** [comment]
Writing some notes for myself/the implementer.

> You cannot create a sparse file by calling CreateFile with FILE_ATTRIBUTE_SPARSE_FILE in the dwFlagsAndAttributes parameter. You must use the FSCTL_SET_SPARSE control code. [via the DeviceIoControl function] [Example Invocation](https://docs.microsoft.com/en-us/windows/win32/devio/calling-deviceiocontrol)

> The only way to clear this attribute [set as not sparse] is to overwrite the file (for example, by calling the CreateFile function with the CREATE_ALWAYS flag).

**Comment by RangerMauve** [comment]
Currently don't have bandwidth or an urgent need to work on this since priorities got shifted from when I investigated before. Would be down to help folks figure it out if they have time though.
