### ISSUE TITLE
fswin fails to build on Linux or MacOS

### ISSUE THREAD

**Issue by aminya** [xxoo/node-fswin#26]
Shouldn't node-fswin generate a dummy .node file so it can be required from different operating systems? 

Linux:
```
[Error: Error: Not a valid ELF file: /home/vsts/work/1/s/out/app/node_modules/fswin/node/x64/fswin.node
```

MacOS
```
[Error: Error: /Users/runner/work/1/s/out/app/node_modules/fswin/node/x64/fswin.node: file is neither a fat binary file nor a Mach-O object file
```

**Comment by xxoo** [comment]
the npm package is using a index.js to detect os, that makes `require('fswin')` avoids loading `fswin.node` when `process.platform` is not `win32`.
could you supply some code to reproduce the error?
```
% node -e "console.log(require('fswin'))"
null
```

**Comment by aminya** [comment]
@xxoo Did this package had this issue in older versions? 

See the CI errors in 
https://github.visualstudio.com/Atom/_build/results?buildId=92731&view=logs&j=e2cf4b02-5697-54ad-cf7c-fc2a840d53af&t=9fd275d3-5d0a-5af8-58ae-a01a7d61dbd5&l=39

https://github.com/atom/atom/pull/21777

I am updating fswin just in case if that is solved in the newer versions.

**Comment by xxoo** [comment]
@aminya i don't think so. `index.js` has been unchanged for over 2 years.
the log says it was trying to load `fswin/node/ia32/fswin.node`. which means `process.platform` is `win32`, `process.arch` is `ia32` and `process.versions.electron` is equal to `false`. however the script was definitely not running on windows. in my opinion, that just doesn't make sense. there must be something wrong with the environment.
this is the source code of `index.js` 
```javascript
'use strict';
if (process.platform === 'win32') {
	module.exports = require((process.versions && process.versions.electron ? './electron/' : './node/') + process.arch + '/fswin.node');
} else {
	module.exports = null;
}
```

**Comment by aminya** [comment]
winattr package is out of date. I have fixed it in [this PR](https://github.com/stevenvachon/winattr/pull/12). It is published in my @aminya/winattr package.

**Comment by xxoo** [comment]
does it solve the problem? if so i'd like to close this issue

**Comment by aminya** [comment]
It takes some time until I can give you a solid answer. 

This PR should be merged, and then it should be merged to Atom itself.
https://github.com/atom/text-buffer/pull/336/

**Comment by aminya** [comment]
We still hit the error https://github.com/atom/text-buffer/pull/336#issuecomment-747224266

**Comment by xxoo** [comment]
i see. seems there's nothing i  can do for that...
