### ISSUE TITLE
OneDrive offline files have IS_OFFLINE: false attribute

### ISSUE THREAD

**Issue by aleksey-hoffman** [xxoo/node-fswin#28]
Hi, thanks for making this module.

I found a problem with `getAttributes` functions, they return `IS_OFFLINE: false` for files located in OneDrive directory with status "Available when online". They have `compressedSize === 0`

**Comment by xxoo** [comment]
those 2 attributes are added now.

**Comment by aleksey-hoffman** [comment]
@xxoo oh wow, you work quick! Thank you brother. 
I will test it now. I'm using your module in my open-source [file manager app](https://github.com/aleksey-hoffman/sigma-file-manager).

It seems that OneDrive utilizes [attributes](https://www.cloudappie.nl/powershell-get-onedrive-syncstatus/) like `5248544` (not available locally) `525344` (always available), `ReparsePoint` (available but it might be deleted)

Powershell:

```
Get-ChildItem "C:\Users\USERNAME\OneDrive\"  -file -recurse | Select-Object FullName,Attributes
```

**Comment by aleksey-hoffman** [comment]
I tested the `getAttributesSync` function on a few OneDrive files with different statuses. There's some differences between `Powershell` and `getAttributesSync `outputs I'm not sure if that's the expected results or not.

- reparsePoint attribute values don't match (`true` in Powershell; `false` in getAttributesSync)
- IS_RECALL_ON_OPEN is `false` for all 3 files with different statuses.

The IS_RECALL_ON_DATA_ACCESS attribute seems to be working correctly, it's `true` for offline files,

## Test data

![image](https://user-images.githubusercontent.com/61761672/131827659-5bf989ee-d583-4b01-b343-cbda38822fee.png)


## Output from Powershell:

```
Get-ChildItem "C:\Users\USERNAME\OneDrive\"  -file -recurse | Select-Object FullName,Attributes
```

```
C:\Users\alex\OneDrive\Pictures\1.jpg                        5248544
C:\Users\alex\OneDrive\Pictures\2.jpg                        525344
C:\Users\alex\OneDrive\Pictures\3.jpg                        ReparsePoint
```


## Output from `getAttributesSync`  
```
fswin.getAttributesSync('C:/Users/alex/OneDrive/Pictures/1.jpg')          
  SIZE: 608779,
  RAW_ATTRIBUTES: 5242912,
  IS_ARCHIVED: true,
  IS_COMPRESSED: false,
  IS_DEVICE: false,
  IS_DIRECTORY: false,
  IS_ENCRYPTED: false,
  IS_HIDDEN: false,
  IS_NOT_CONTENT_INDEXED: false,
  IS_OFFLINE: false,
  IS_READ_ONLY: false,
  IS_SPARSE_FILE: false,
  IS_SYSTEM: false,
  IS_TEMPORARY: false,
  IS_INTEGRITY_STREAM: false,
  IS_NO_SCRUB_DATA: false,
  IS_RECALL_ON_DATA_ACCESS: true,
  IS_RECALL_ON_OPEN: false,
  IS_REPARSE_POINT: false
  
fswin.getAttributesSync('C:/Users/alex/OneDrive/Pictures/2.jpg')          
  SIZE: 282673,
  RAW_ATTRIBUTES: 524320,
  IS_ARCHIVED: true,
  IS_COMPRESSED: false,
  IS_DEVICE: false,
  IS_DIRECTORY: false,
  IS_ENCRYPTED: false,
  IS_HIDDEN: false,
  IS_NOT_CONTENT_INDEXED: false,
  IS_OFFLINE: false,
  IS_READ_ONLY: false,
  IS_SPARSE_FILE: false,
  IS_SYSTEM: false,
  IS_TEMPORARY: false,
  IS_INTEGRITY_STREAM: false,
  IS_NO_SCRUB_DATA: false,
  IS_RECALL_ON_DATA_ACCESS: false,
  IS_RECALL_ON_OPEN: false,
  IS_REPARSE_POINT: false
  
fswin.getAttributesSync('C:/Users/alex/OneDrive/Pictures/3.jpg')          
  SIZE: 431368,
  RAW_ATTRIBUTES: 32,
  IS_ARCHIVED: true,
  IS_COMPRESSED: false,
  IS_DEVICE: false,
  IS_DIRECTORY: false,
  IS_ENCRYPTED: false,
  IS_HIDDEN: false,
  IS_NOT_CONTENT_INDEXED: false,
  IS_OFFLINE: false,
  IS_READ_ONLY: false,
  IS_SPARSE_FILE: false,
  IS_SYSTEM: false,
  IS_TEMPORARY: false,
  IS_INTEGRITY_STREAM: false,
  IS_NO_SCRUB_DATA: false,
  IS_RECALL_ON_DATA_ACCESS: false,
  IS_RECALL_ON_OPEN: false,
  IS_REPARSE_POINT: false
```

**Comment by xxoo** [comment]
well i think i get it now. according to [MSDN](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlsetthreadplaceholdercompatibilitymode) windows can lie about file attributes to certain applications for compatibility reason. nodejs is probably one of them. to fix that we need to implant the api mentioned above. and let the user decide whether buying these lies.

**Comment by aleksey-hoffman** [comment]
Well, that's unfortunate.
Does it show the same output if you build a C++ console exe instead of a Node module?

**Comment by xxoo** [comment]
i did not make a standalone exe for testing, but i did test that api and it works fine. `RAW_ATTRIBUTES` can show the same value as powershell does. but i was still too naive. it is not possible to let user decide whether showing the real attributes by implanting that api. since the api only changes the current thread. but a async call runs in a random background thread. there is no guarantee that 2 async calls would run in the same thread. i guess the best thing we can do for now is to make sure the user gets the truth, other things are less important.

**Comment by xxoo** [comment]
@aleksey-hoffman it's updated again. everything should be find this time. and i suggest u to use `fswin.find` instead of `fswin.getAttributes` cause `REPARSE_POINT_TAG` could also be useful

**Comment by aleksey-hoffman** [comment]
@xxoo thank you, I just tested it:

- `IS_OFFLINE` attribute returns correct information
- `IS_PINNED` attribute returns correct information
- `IS_UNPINNED` attribute returns correct information
- `RAW_ATTRIBUTES` attribute returns correct information
- `REPARSE_POINT_TAG` attribute returns `CLOUD_6` for `RAW_ATTRIBUTE: 1056` and  `RAW_ATTRIBUTE: 525344`; and returns `CLOUD_4` for `RAW_ATTRIBUTE: 5248544` (offline files). Not sure what cloud 6 and 4 means.

With these attributes, you can now definitely get correct cloud file status. Thanks!

## Test data

![image](https://user-images.githubusercontent.com/61761672/131827659-5bf989ee-d583-4b01-b343-cbda38822fee.png)

```
[
  {
    LONG_NAME: '1.jpg',
    SHORT_NAME: '',
    CREATION_TIME: 2021-09-01T15:07:54.716Z,
    LAST_ACCESS_TIME: 2021-09-03T18:23:59.287Z,
    LAST_WRITE_TIME: 2021-03-24T13:15:17.000Z,
    SIZE: 608779,
    RAW_ATTRIBUTES: 5248544,
    IS_ARCHIVED: true,
    IS_COMPRESSED: false,
    IS_DEVICE: false,
    IS_DIRECTORY: false,
    IS_ENCRYPTED: false,
    IS_HIDDEN: false,
    IS_NOT_CONTENT_INDEXED: false,
    IS_OFFLINE: true,
    IS_READ_ONLY: false,
    IS_SPARSE_FILE: true,
    IS_SYSTEM: false,
    IS_TEMPORARY: false,
    IS_INTEGRITY_STREAM: false,
    IS_NO_SCRUB_DATA: false,
    IS_RECALL_ON_DATA_ACCESS: true,
    IS_RECALL_ON_OPEN: false,
    IS_VIRTUAL: false,
    IS_EA: false,
    IS_PINNED: false,
    IS_UNPINNED: true,
    REPARSE_POINT_TAG: 'CLOUD_4'
  }
]
[
  {
    LONG_NAME: '2.jpg',
    SHORT_NAME: '',
    CREATION_TIME: 2021-09-01T15:07:54.723Z,
    LAST_ACCESS_TIME: 2021-09-03T18:20:20.823Z,
    LAST_WRITE_TIME: 2021-03-24T13:53:50.000Z,
    SIZE: 282673,
    RAW_ATTRIBUTES: 525344,
    IS_ARCHIVED: true,
    IS_COMPRESSED: false,
    IS_DEVICE: false,
    IS_DIRECTORY: false,
    IS_ENCRYPTED: false,
    IS_HIDDEN: false,
    IS_NOT_CONTENT_INDEXED: false,
    IS_OFFLINE: false,
    IS_READ_ONLY: false,
    IS_SPARSE_FILE: false,
    IS_SYSTEM: false,
    IS_TEMPORARY: false,
    IS_INTEGRITY_STREAM: false,
    IS_NO_SCRUB_DATA: false,
    IS_RECALL_ON_DATA_ACCESS: false,
    IS_RECALL_ON_OPEN: false,
    IS_VIRTUAL: false,
    IS_EA: false,
    IS_PINNED: true,
    IS_UNPINNED: false,
    REPARSE_POINT_TAG: 'CLOUD_6'
  }
]
[
  {
    LONG_NAME: '3.jpg',
    SHORT_NAME: '',
    CREATION_TIME: 2021-09-01T15:07:54.729Z,
    LAST_ACCESS_TIME: 2021-09-03T18:20:26.297Z,
    LAST_WRITE_TIME: 2021-05-18T09:51:45.000Z,
    SIZE: 431368,
    RAW_ATTRIBUTES: 1056,
    IS_ARCHIVED: true,
    IS_COMPRESSED: false,
    IS_DEVICE: false,
    IS_DIRECTORY: false,
    IS_ENCRYPTED: false,
    IS_HIDDEN: false,
    IS_NOT_CONTENT_INDEXED: false,
    IS_OFFLINE: false,
    IS_READ_ONLY: false,
    IS_SPARSE_FILE: false,
    IS_SYSTEM: false,
    IS_TEMPORARY: false,
    IS_INTEGRITY_STREAM: false,
    IS_NO_SCRUB_DATA: false,
    IS_RECALL_ON_DATA_ACCESS: false,
    IS_RECALL_ON_OPEN: false,
    IS_VIRTUAL: false,
    IS_EA: false,
    IS_PINNED: false,
    IS_UNPINNED: false,
    REPARSE_POINT_TAG: 'CLOUD_6'
  }
]
```
