### ISSUE TITLE
New functions

### ISSUE THREAD

**Issue by aleksey-hoffman** [xxoo/node-fswin#29]
I wanted to ask, have you ever considered expanding this module by adding more functions for working with file system and drives?

For example:

- `getLogicalDriveList`
- `watchDriveList` (to detect when drive list changes)
- `getDriveInfo` (memory type, name, file system, etc.)
- `getUsbDevices`
- `ejectDrive`
- `setDriveLabel`
- `copyToMtpDevice`
- `readMtpDevice` 

Maybe some functions from this [systeminformation](https://systeminformation.io/) module? 
It's a good module but it's really slow since it's using Powershell calls instead of C++:
- It [takes 100ms](https://github.com/sebhildebrandt/systeminformation/issues/429) to get the drive list
- And it [doesn't encode](https://github.com/sebhildebrandt/systeminformation/issues/548) strings in UTF-8, which means you cannot use it if drives have non-ASCII characters in their name

This module could become really popular if it had a lot more functions.

**Comment by xxoo** [comment]
sure. i made this module to fit my own needs before. but patches and prs are always welcome. these functions seems useful but i still need sometime to see if i can do the job.

**Comment by aleksey-hoffman** [comment]
Hi @xxoo I noticed that `find()` doesn't return link type property (symlink, hardlink).
Can `fswin` module determine whether a file is a hardlink right now?

**Powershell**
```
mklink /h "./test sym link.txt" "./test.txt"
mklink /h "./test hard link.txt" "./test.txt"
Get-ChildItem | select name, linktype
```

**Output**:

```
Name:                  LinkType:
-----                  ---------
test sym link.txt      SymbolicLink
test hard link.txt     HardLink
test.txt               HardLink
```

**Comment by xxoo** [comment]
you may detect symlinks by checking `REPARSE_POINT_TAG` for `SYMLINK`. but hardlinks are quite different. cause every regular file is a hardlink. multiple files may point the same position in filesystem. there is a win32 api can get the link count of a file. and it's possible to include that field in `getAttributes`, however not in `find`

**Comment by xxoo** [comment]
`LINK_COUNT` is added to `getAttributes` now. please note that a symlink can also have multiple hardlinks

**Comment by aleksey-hoffman** [comment]
@xxoo that's great, thank you very much! 
The code changes look good to me. I will update the module in my app, test it and implement the hardlink info getter today

**Comment by xxoo** [comment]
@aleksey-hoffman added 4 new functions `getLogicalDriveList `, `getVolumeInformation`, `setVolumeLabel` and `ejectDrive`. docs are also add to wiki

**Comment by aleksey-hoffman** [comment]
@xxoo that's great, good job brother! 
I will check the commits and add some of those functions into my app later.

I found one issue with `ejectDriveSync` functon:

```js
// Test config: removable USB drive, letter D

// Nothing happens, returns true
fswin.ejectDriveSync('d', 2)

// Works as expected, drive gets ejected, similarly to Windows built-in eject function
fswin.ejectDrive('d', 2, console.log)
```

Thanks for your hard work on this module. I just mentioned `xxoo/node-fswin` on the readme page of my app, hopefully it will help increase the popularity of `fswin` a little bit, when the app gets more popular:
https://github.com/aleksey-hoffman/sigma-file-manager#special-thanks

Can I support your work financially somehow? Do you have a Patreon / Buymeacoffee page or Paypal link?
Maybe you should consider adding support links to the readme page similarly to my app's readme page, so people could support your work?:
https://github.com/aleksey-hoffman/sigma-file-manager#supporters

**Comment by xxoo** [comment]
thanks bro you are so kind😄 i will consider about adding some donation link.
now i think i should look into this issue. sync functions are easier to use, it would be better to keep them unless i can't find a way to fix that.

**Comment by xxoo** [comment]
@aleksey-hoffman i can not reproduce it...
could u make more tests with different methods and let me know the result?

**Comment by aleksey-hoffman** [comment]
@xxoo I discovered something weird while re-testing it. I noticed that the function was not working when I was measuring execution time of other functions using `console.time` above the `fswin.ejectDriveSync` function line.

### Test code 1
Result: ❌ Nothing happens, returns true 
```js
console.time('time:')
// Any code here
console.timeEnd('time:')

console.log(fswin.ejectDriveSync('D', 0))
```

### Test code 2
Move  `console.time` below the `fswin.ejectDriveSync` function

Result: ✅ Works as expected, returns true 
```js
console.log(fswin.ejectDriveSync('D', 0))

console.time('time:')
// Any code here
console.timeEnd('time:')
```

### Test code 3
Result: ✅ Works as expected, returns true 

```js
console.log(fswin.ejectDriveSync('D', 0))
```

I never saw anything like this, I have no idea why  `console.time` breaks the `fswin.ejectDriveSync` function, even though it returns `true` anyway.

Sorry for reporting this as a problem with `fswin.ejectDriveSync` function, I didn't realize that `console.time` was causing the issue. 

### Other functions:

1. `getLogicalDriveList` returns `FIXED` for external HDD drive that connects via USB. When this drive is connected Windows displays "safely eject" icon in Tray , however in the drive properties, it says "local disk", not "USB drive". That's probably why Windows returns `FIXED` to C++ API

2. `setVolumeLabel` is not working for `FIXED` drives (however it works with external HDD USB drive that I mentioned in the line above, even though it is reported as `FIXED`). 

I think it's because `FIXED` drives require administrator rights. When I run a similar command via powershell I get "Access is denied" error:

#### powershell
```shell
function ChangeDriveLabel([string]$driveletter,[string]$newlabel )
{
     $disk = Get-WmiObject -Class win32_volume -Filter "DriveLetter = '$driveletter'"
     Set-WmiInstance -input $disk -Arguments @{ Label=$newlabel}
}
ChangeDriveLabel -driveletter 'C:' -newlabel 'test'
```

```
Set-WmiInstance : Access is denied.
``` 

#### powershell

But If I run this function below, I get a system prompt, allowing me to execute the command:

```
(New-Object -ComObject shell.application).NameSpace("C:\").self.name = "test"
```

![image](https://user-images.githubusercontent.com/61761672/136106676-6766dad6-acbc-4eb5-8238-888b4d084050.png)

**Comment by aleksey-hoffman** [comment]
@xxoo I tested it the new version, here's the results:

After upgrading to `v3.21.1014` I get this error:

```
fswin.getDriveParentDeviceSync is not a function
```

The new `getStorageProperties` function returns `null`:

```
// var path = '\\\\.\\PhysicalDrive0';
var path = '\\\\.\\PHYSICALDRIVE0';
var properties = {
  deviceProperty: true,
  adapterProperty: true,
  deviceWriteCacheProperty: true,
  accessAlignmentProperty: true,
  deviceSeekPenalty: true,
  deviceTrim: true,
  deviceLBProvisioningProperty: true,
  devicePowerProperty: true,
  deviceCopyOffloadProperty: true,
  deviceMediumProductType: true,
  adapterRpmbProperty: true,
  deviceIoCapabilityProperty: true,
  adapterTemperatureProperty: true,
  deviceTemperatureProperty: true,
  adapterSerialNumber: true
};

console.log(fswin.getStoragePropertiesSync(path, properties));
// null

fswin.getStorageProperties(path, properties, console.log);
// null
