### ISSUE TITLE
getCompressedSize: get size of inaccessible files

### ISSUE THREAD

**Issue by aleksey-hoffman** [xxoo/node-fswin#32]
Hi @xxoo is it possible to make `getCompressedSize` function return the size even for inaccessible files?

I calculated the size of all files in `C:\Windows` and got `1.9 GB` with `getCompressedSizeSync` while the File Explorer showed `27.2 GB` in the properties window.
I assume the difference is due to inaccessible files.

![image](https://user-images.githubusercontent.com/61761672/171745526-56e3203c-4710-422d-b8ed-548e317c0b1f.png)

**Comment by aleksey-hoffman** [comment]
Perhaps a similar handle to [this Libuv implementation](https://github.com/libuv/libuv/pull/3268)?

**Comment by xxoo** [comment]
i don't think that's possible cause `getCompressedSize` does not depend on `CreateFileW`. not directly at least. only `GetCompressedFileSizeW` is used and it has no option for file access mode. and i guess it would not ask for write permission anyway. perhaps you can use run as admin to achieve this.
