### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by felipecrs** [xxoo/node-fswin#33]
It would be really nice if this library could ship its types. :)

![image](https://user-images.githubusercontent.com/29582865/197643184-411311f0-0fc9-4e71-8a6f-968a679d2d2c.png)

**Comment by xxoo** [comment]
ok I'll add the type definitions as time permits

**Comment by kihlh** [comment]
**I have written the type declaration, you can check this**
https://www.npmjs.com/package/fswin-types

**Comment by xxoo** [comment]
new npm package with type definitions now released.
the credit goes to @7fold

**Comment by ShenHongFei** [comment]
https://www.npmjs.com/package/fswin?activeTab=explore
index.d.ts should also be published to npm, but there is no such file in the npm repository, so the type definition cannot be found after installing the fswin package.

**Comment by xxoo** [comment]
@ShenHongFei sorry i forgot that... it's fixed now. please check updates
