### ISSUE TITLE
Can it be built with the latest version of Node.js?

### ISSUE THREAD

**Issue by KaminoRyo** [xxoo/node-fswin#36]
Hi. I'm facing [an issue](https://github.com/stevenvachon/hidefile/issues/12#issue-2083504358) using a library that depends on an older version of `fswin`.
I am considering forking, patching, or creating a custom solution, but is the latest version of `fswin` buildable with the latest Node.js? (v20-21)

**Comment by xxoo** [comment]
It should be buildable. But it's not necessary to build fswin if you don't need to modify the source.
Using the latest version of fswin on npm should be just fine. It contains binaries of all arches.

**Comment by KaminoRyo** [comment]
Sorry, my text was vague. Of course, fswin itself will not be built. I don't have much knowledge about C++, OS APIs, or file systems...
"Are there any restrictions on building an application that includes the latest fswin (from npm) using the latest node.js?" That's what I meant. Thank you.

**Comment by xxoo** [comment]
There's only one condition for fswin 3.x. n-api support, which exists in nodejs 8.0 or later.
Older versions have very limited nodejs support. You can see it in `node_modules/fswin` directory
