### ISSUE TITLE
Use correct SPDX license tag

### ISSUE THREAD

**Issue by szimmer-dap** [xxoo/node-fswin#37]
Hi there!

**Description of the Problem:**
Your package uses “BSD” as license entry in package.json. However, given that there so many variants of the BSD-license (from BSD Zero Clause to BSD 4 Clause + their derivatives), simply using “BSD” is ambiguous and hence not a valid SPDX identifier (see https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-list/ for a complete list of valid SPDX identifiers).
Looking at the LICENSE file, it seems that you actually intend to use the MIT License instead of BSD. This should be corrected in your package’s metadata.

**Possible Solution:**
Please use a valid SPDX identifier instead. Looking at the LICENSE file, it seems that you intend to use the MIT License. The corresponding SPDX identifier for this would be “MIT”. So if you change the line `"license": "BSD "` to `"license": "MIT"` within [package.json](https://github.com/xxoo/node-fswin/blob/722895f46cd0ffd37ce178b9d69ba5ac812e349b/package.json#L24), that would resolve the problem.
Additional LICENSE files or license infos in README files can remain as they are, as long as they don't contradict the content of the "license" entry.

**Why is this relevant?**
We are currently adapting a package approval workflow, where packages are approved or blocked based on certain criteria. One very important criterion is the package's license. There is a list of approved licenses (like MIT, Apache, ...) and a list of licenses that cannot be used (like GPL).
Having correct license metadata for each package would be a huge help for us, because with incorrect SPDX tags or embedded license files we have to manually check and approve every single version of every package.

**Comment by xxoo** [comment]
Thanks for reminding me
The license field in package.json is fixed now
