### ISSUE TITLE
The definition of DriveType can be adjusted

### ISSUE THREAD

**Issue by michael5107414** [xxoo/node-fswin#39]
Hi,

Based on the implementation found [here](https://github.com/xxoo/node-fswin/blob/master/src/getLogicalDriveList.h#L110), `export type DriveType = 'NO_ROOT_DIR' | 'REMOVABLE' | 'FIXED' | 'REMOTE' | 'CDROM' | 'RAMDISK' | 'UNKNOWN'` would be a more accurate representation. If you agree with this change, I'd be happy to create a PR to update it.

**Comment by xxoo** [comment]
Of course I appreciate that
There may be other types that can be improved in a similar way. You may do the same if possible

**Comment by xxoo** [comment]
Thanks for your work!
The npm package is also updated now
