### ISSUE TITLE
package.json tags

### ISSUE THREAD

**Issue by stevenvachon** [xxoo/node-fswin#7]
I couldn't find the package.json in the repo, so I couldn't send a pull request.

I think it'd be beneficial to you and the library if you added an "fs" tag to the package.json file

**Comment by xxoo** [comment]
ok, i'll add this tag in the next release.
this file is not necessary in the repo since the npm package does not contain source code anymore.

**Comment by stevenvachon** [comment]
Where do you keep the source code now?

**Comment by xxoo** [comment]
just in the repository of course.
but the npm package is not a part of this repo.

**Comment by stevenvachon** [comment]
Oh, right, sorry.
Where is the package.json stored, then? Just on npm servers and you pull it for every release?

**Comment by xxoo** [comment]
only in npm package. i always have a local copy of that.
and i manually update the binaries every time before pushing to npm server.
the package also can be found here: http://xxoo.github.io/node-fswin/fswin.7z
