### ISSUE TITLE
does not work with io.js

### ISSUE THREAD

**Issue by stevenvachon** [xxoo/node-fswin#8]
It looks for a `./2.0.x/` dir which does not exist. v1.0.x will undoubtedly have the same issue.

This would come in handy: https://github.com/nodejs/io.js/pull/493

**Comment by xxoo** [comment]
i think it's not just a path issue. io and node are currently using different version of v8. which means there might be some kind of compatibility problem for native modules.
and i heard that they would merge into a single project in the near future. that's truly a good thing. perhaps we should wait for that.

**Comment by stevenvachon** [comment]
They *might* merge.

**Comment by stevenvachon** [comment]
And even if they do merge, the version of V8 will be the same as iojs

**Comment by stevenvachon** [comment]
Please let me know if you're going to be working on this in the near future so that I can decide to release v1.0 of my library or wait (to avoid a v2.0 too soon).

**Comment by stevenvachon** [comment]
http://www.infoq.com/news/2015/05/nodejs-iojs

**Comment by xxoo** [comment]
sorry i didn't have enough time for this project. but i think i will make it work with io.js in the next release. probably in one or two weeks.
thanks to all io.js contributors. javascript now has a more brighten future.

**Comment by stevenvachon** [comment]
Perhaps this will at least be informative: https://gist.github.com/maxogden/e81e0f1d222106146828

**Comment by xxoo** [comment]
iojs support is finally added...
but i just made some test on version 2.5

**Comment by stevenvachon** [comment]
Thanks!

By the way, v3.0.0 was just released.
