### ISSUE TITLE
How to check if binding is broken?

### ISSUE THREAD

**Issue by stevenvachon** [xxoo/node-fswin#9]
In [a library I've written](https://github.com/stevenvachon/winattr) that wraps fswin, I've been thinking of using this:
```js
try {
    fswin.getAttributes(...);
} catch(e) {
    if (e.message === "The specified procedure could not be found.") {
        // binding error
        child_process_attrib_fallback(...);
    } else {
        // expected error
        throw error;
    }
}
```
I think this is a Windows error. Are there any other errors that I can check for in the event that fswin has loaded (./x.x.x/arch/ exists) but fails to run? I'm trying to be very thorough with my lib and load a shell fallback if anything happens (due to the nature of bindings).

**Comment by xxoo** [comment]
i think this error is gone for now :)
